version: "3"
services:
  bot:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: map-bot
  api:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile-api
    container_name: map-api
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
